title: Rating
tagline: "RATING TAGLINE"
description: "RATING DESCRIPTION"
url: "//flipboxfactory.com/plugins/craft/rating"
theme: "//s3.amazonaws.com/theme.flipboxfactory.com/v1"
google_analytics_tracking_id: XX-XXXXXXXX-X