title: Rating
tagline: "RATING TAGLINE"
description: "RATING DESCRIPTION"
url: "https://flipboxfactory.com/plugins/craft/rating"
theme: "http://theme.flipboxfactory.com/v1"
google_analytics_tracking_id: XX-XXXXXXXX-X